### ISSUE TITLE
QXcbConnection: XCB error:145 (Unknown), sequence: 171, resource id: 0, major code: 139 (Unknown), minor code: 20

### ISSUE THREAD

**Issue by v-wewei** [dukebw/lintel#27]
i install the linetl using conda-forge , but get this error when using lintel_test video.mp4 --width 0 --height 0. And it return with a result 0.051499......., but follow with this error, i need your help for this error.could you please help me to solve this problem?

**Comment by dukebw** [comment]
Hi, could you give me a bit of information about your system configuration?

**Comment by v-wewei** [comment]
Hi,Bredan Duke




I am writing to ask a question , does lintel support to extract key frame in a video just like opencv ? 

if i need to modify the code of lintel for key frame extracting, where should me modify?

thanks very much!Lintel is really faster than opencv in most cases.




Thanks,

Wei Wei


-----Original Messages-----

**Comment by dukebw** [comment]
Hi Wei Wei,

Since @kli-nlpr (https://github.com/dukebw/lintel/issues/23) also expressed interest, I would like to add keyframe extraction support to Lintel, however lately I have little free time to research into how to do this.

Sorry, I would have to read into how FFmpeg is handling keyframes. It may be as simple as checking a flag in the AVFrame returned by `receive_frame` (`vid_ctx->frame`), but I don't know.

**Comment by v-wewei** [comment]
thanks very much ,hope you can improve lintel as expected if you have time.

I will read your code, and try to extract key frame, but i do not have much background knowledge on c and c++, i don't have much confidence in finishing that.




thanks for providing such a good tool for video task, i will recommend it to my friends.

 



-----Original Messages-----
