### ISSUE TITLE
Error running lintel_test

### ISSUE THREAD

**Issue by piergiaj** [dukebw/lintel#5]
Some videos work, some give the following error:
```python: lintel/py_ext/lintelmodule.c:134: setup_vid_stream_context: Assertion `(video_stream->duration > 0) && (video_stream->nb_frames > 0)' failed.```

Others simply give ```Segmentation fault (core dumped)``` and nothing else. They are all videos downloaded from youtube.

I installed ffmpeg from source using your instructions and ffmpeg is able to extract frames from these videos using
```ffmpeg -i vid.mp4 %05d.jpg```

Any idea what the problem is? Did I build something wrong?

**Comment by dukebw** [comment]
Hmm, would you be able to give me the URL of any of the videos? I can see if I can reproduce the issue.

**Comment by piergiaj** [comment]
Sure, two that are giving me those errors are:
youtube.com/watch?v=YSes0R7EksY
https://www.youtube.com/watch?v=zLLh104pkeg

**Comment by dukebw** [comment]
Okay I am able to reproduce the error. What happens is, `find_video_stream_index` here:

https://github.com/dukebw/lintel/blob/f01944682a7bb525bf0323f33b972d3de6f5877c/lintel/core/video_decode.c#L378

returns a stream index for a video stream for which either `video_stream->duration <= 0` or `video_stream->nb_frames <= 0`, and the code hits an assert here:

https://github.com/dukebw/lintel/blob/f01944682a7bb525bf0323f33b972d3de6f5877c/lintel/py_ext/lintelmodule.c#L134

Anyway, I wonder if these videos were encoded in a way that FFmpeg can't figure out how many frames they have.

Once I converted the video using FFmpeg, via `ffmpeg -i Ultimate\ BLT\ Sandwich\ Recipe\ -\ SORTED-YSes0R7EksY.webm test.mp4`, I was able to run `lintel_test` fine.

My steps were:

1. Use youtube-dl to download the video: `youtube-dl https://youtube.com/watch?v=YSes0R7EksY`

2. Use ffmpeg to convert to mp4 (just converting to webm might also work): `ffmpeg -i Ultimate\ BLT\ Sandwich\ Recipe\ -\ SORTED-YSes0R7EksY.webm test.mp4`

I just renamed it to `test.mp4`.

3. Then run `lintel_test`: `lintel_test --filename test.mp4 --width 1920 --height 1080`.

Would converting the videos before using lintel be a viable option for you?

Otherwise, I will look into the bug and see how FFmpeg handles this kind of video without `duration` or `nb_frames` information.

**Comment by dukebw** [comment]
Right now lintel doesn't support resizing, because my workflow has always been to (as you suggest) first use FFmpeg to convert and scale videos to a set size expected by the input pipeline, store those in a serialized format (HDF5), and then use lintel in the input pipeline to decode the converted/scaled videos on the fly. I do think this has the added performance benefit of reducing the size of the video, which will take away much of the I/O pressure.

Do you have a use case in mind that would require you to resize video on the fly, i.e., there would be no way to pre-process all the videos to a fixed size? If that's the case, I can definitely add support for resizing. I believe this should take just a bit of work. I could also add support for dynamically determining height and width.

Either way, I definitely agree that lintel shouldn't just explode when the wrong width/height is passed. I added this to the Projects on this GitHub already, to make the behaviour more reasonable (i.e., return a Python exception) when errors are found.

**Comment by piergiaj** [comment]
I don't really need resizing on the fly, doing that first using ffmpeg is easy enough and greatly reduces the storage space, and saving as videos is significantly smaller than saving frames.

However, dynamically determining height and width would be super useful. I tried to add that myself, but in the process I broke something with ffmpeg and I can't build anything anymore. I will share the code with you once I get the dependencies and building figured out and the code tested and working.

My main use case for this that I resize all the videos so the shortest size is 256 and maintain the aspect ratio. This is helpful for charades, because many videos are taken on phones with very non-square aspect rations. I then do random cropping after loading to get the 224x224 (or whatever) size input I want. Some charades videos are landscape and some are portrait, and it'd be nice to have lintel return the frames whatever size they are so I can crop them. 

The HDF5 route isn't best for my current method. I'm hoping to get lintel setup and working so I can load frames directly from videos. It is fast enough and the models are large enough that the GPU will still be the bottleneck. lintel will just save significant storage space compared to saving individual frames.
